import { useState } from 'react';
import { Button, Dialog, DialogActions, DialogContent, DialogTitle, Grid, MenuItem, Stack, TextField, Typography } from '@mui/material';
import type { Account, Loan } from '@kippa/domain';
import { loanInputSchema, type LoanInput } from '@/libs/loans';

type Props = { accounts: Account[]; loan: Loan | null; open: boolean; busy: boolean; onClose: () => void; onSave: (input: LoanInput) => Promise<void> };
const empty = (): LoanInput => ({ name: '', currency: 'EGP', originalTotal: 0, installmentAmount: 0, totalInstallments: 36, openingPaidInstallments: 0, openingPaidAmount: 0, firstPaymentDate: new Date().toISOString().slice(0, 10), dueDay: 1, graceDay: 2, paymentAccountId: '', status: 'active', notes: null });

export function LoanDialog({ accounts, loan, open, busy, onClose, onSave }: Props) {
  const [values, setValues] = useState<LoanInput>(() => loan ? { name: loan.name, currency: loan.currency, originalTotal: loan.originalTotal, installmentAmount: loan.installmentAmount, totalInstallments: loan.totalInstallments, openingPaidInstallments: loan.openingPaidInstallments ?? 0, openingPaidAmount: loan.openingPaidAmount ?? 0, firstPaymentDate: loan.firstPaymentDate, dueDay: loan.dueDay, graceDay: loan.graceDay ?? null, paymentAccountId: loan.paymentAccountId, status: loan.status, notes: loan.notes ?? null } : empty()); const [error, setError] = useState('');
  const set = (key: keyof LoanInput, value: LoanInput[keyof LoanInput]) => setValues(current => ({ ...current, [key]: value }));
  const number = (key: keyof LoanInput) => (event: React.ChangeEvent<HTMLInputElement>) => set(key, Number(event.target.value));
  const submit = async () => { const parsed = loanInputSchema.safeParse(values); if (!parsed.success) { setError(parsed.error.issues[0]?.message ?? 'Check the loan details.'); return; } setError(''); await onSave(parsed.data); };
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm">
    <DialogTitle>{loan ? 'Edit loan' : 'Add loan'}<Typography component="span" variant="fieldHint" color="text.secondary" display="block">Set the fixed schedule once; Kippa will prepare every cycle.</Typography></DialogTitle>
    <DialogContent dividers><Stack spacing={2.5} sx={{ mt: 1 }}>
      <Stack spacing={2}><Typography variant="sectionLabel">Loan details</Typography><TextField autoFocus fullWidth label="Loan name" value={values.name} onChange={e => set('name', e.target.value)} /><Grid container spacing={2}><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth type="number" label="Fixed monthly payment" value={values.installmentAmount || ''} onChange={number('installmentAmount')} /></Grid><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth type="number" label="Number of months" value={values.totalInstallments} onChange={number('totalInstallments')} /></Grid></Grid><TextField fullWidth type="number" label="Contract total" value={values.originalTotal || ''} onChange={number('originalTotal')} helperText="For a fixed loan, payment × months." /></Stack>
      <Stack spacing={2}><Typography variant="sectionLabel">Schedule and progress</Typography><Grid container spacing={2}><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth type="date" label="First payment" value={values.firstPaymentDate} onChange={e => set('firstPaymentDate', e.target.value)} slotProps={{ inputLabel: { shrink: true } }} /></Grid><Grid size={{ xs: 6, sm: 3 }}><TextField fullWidth type="number" label="Due day" value={values.dueDay} onChange={number('dueDay')} /></Grid><Grid size={{ xs: 6, sm: 3 }}><TextField fullWidth type="number" label="May withdraw by" value={values.graceDay ?? ''} onChange={number('graceDay')} /></Grid></Grid><Grid container spacing={2}><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth type="number" label="Earlier payments count" value={values.openingPaidInstallments ?? 0} onChange={number('openingPaidInstallments')} /></Grid><Grid size={{ xs: 12, sm: 6 }}><TextField fullWidth type="number" label="Earlier amount paid" value={values.openingPaidAmount ?? 0} onChange={number('openingPaidAmount')} /></Grid></Grid></Stack>
      <Stack spacing={2}><Typography variant="sectionLabel">Payment connection</Typography><TextField select fullWidth label="Paying account" value={values.paymentAccountId} onChange={e => set('paymentAccountId', e.target.value)}>{accounts.filter(a => a.isActive && a.currency === values.currency && a.type !== 'credit').map(a => <MenuItem key={a.id} value={a.id}>{a.name}</MenuItem>)}</TextField></Stack>
      {error && <Typography color="error" variant="body2">{error}</Typography>}
    </Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" loading={busy} onClick={submit}>{loan ? 'Save changes' : 'Add loan'}</Button></DialogActions>
  </Dialog>;
}
