import { useMemo, useState } from 'react';
import { Box, Button, Card, CardContent, Chip, Grid, Paper, Skeleton, Stack, Typography } from '@mui/material';
import type { Loan } from '@kippa/domain';
import { AddIcon, CalendarMonthIcon, EditIcon, PaymentsIcon } from '@/components/AppIcon';
import { Money } from '@/components/Money';
import { PageHeader } from '@/features/shared/components/PageHeader';
import { EmptyLayout } from '@/features/shared/components/EmptyLayout';
import { useAppContext } from '@/hooks/useAppContext';
import { useAccounts, useActiveCycle, useCreateLoanMutation, useLedgerLines, useLoans, useRecordLoanPaymentMutation, useTransactions, useUpdateLoanMutation } from '@/hooks/useFinance';
import { calculateAccountBalance } from '@/libs/financeCalculations';
import { getLoanProgress } from '@/libs/loanCalculations';
import type { LoanInput } from '@/libs/loans';
import { LoanDialog } from './LoanDialog';
import { LoanPaymentDialog } from './LoanPaymentDialog';

export function Loans() {
  const { householdId, userProfile } = useAppContext(); const [editing, setEditing] = useState<Loan | null>(null); const [formOpen, setFormOpen] = useState(false); const [paying, setPaying] = useState<Loan | null>(null);
  const { data: loans = [], isLoading: loansLoading } = useLoans(householdId); const { data: accounts = [], isLoading: accountsLoading } = useAccounts(householdId); const { data: transactions = [], isLoading: txLoading } = useTransactions(householdId); const { data: lines = [], isLoading: linesLoading } = useLedgerLines(householdId); const { data: activeCycle } = useActiveCycle(householdId);
  const createLoan = useCreateLoanMutation(); const updateLoan = useUpdateLoanMutation(); const recordPayment = useRecordLoanPaymentMutation(); const loading = loansLoading || accountsLoading || txLoading || linesLoading;
  const cards = useMemo(() => loans.map(loan => ({ loan, progress: getLoanProgress(loan, transactions, lines), account: accounts.find(a => a.id === loan.paymentAccountId) })), [loans, transactions, lines, accounts]);
  const save = async (input: LoanInput) => { if (editing) await updateLoan.mutateAsync({ householdId, loanId: editing.id, loan: input }); else await createLoan.mutateAsync({ householdId, loan: input }); setFormOpen(false); setEditing(null); };
  const pay = async (amount: number, date: string) => { if (!paying || !userProfile) return; await recordPayment.mutateAsync({ householdId, loanId: paying.id, amount, date, budgetCycleId: activeCycle?.id ?? null, userId: userProfile.uid }); setPaying(null); };
  return <Stack spacing={3}><PageHeader title="Loans" subtitle="Know what is due, keep the account ready, and watch the balance disappear." action={<Button variant="contained" startIcon={<AddIcon />} onClick={() => { setEditing(null); setFormOpen(true); }}>Add loan</Button>} />
    {loading ? <Grid container spacing={2}>{[1,2].map(i => <Grid key={i} size={{ xs: 12, md: 6 }}><Skeleton variant="rounded" height={300} /></Grid>)}</Grid> : cards.length === 0 ? <EmptyLayout icon={<PaymentsIcon />} title="No loans yet" description="Add a fixed loan once and Kippa will reserve every monthly installment automatically." action={<Button variant="contained" onClick={() => setFormOpen(true)}>Add your first loan</Button>} /> : <Grid container spacing={2.5}>{cards.map(({ loan, progress, account }) => { const balance = account ? calculateAccountBalance(account.id, transactions, lines) : 0; const shortfall = Math.max(0, loan.installmentAmount - balance); return <Grid key={loan.id} size={{ xs: 12, lg: 6 }}><Card><CardContent><Stack spacing={2.5}>
      <Stack direction="row" justifyContent="space-between" alignItems="flex-start" spacing={2}><Stack direction="row" spacing={1.5} alignItems="center"><Paper variant="cardHeaderIcon"><PaymentsIcon variant="Bulk" /></Paper><Box><Typography variant="loanTitle">{loan.name}</Typography><Typography variant="loanMeta" color="text.secondary">{progress.paidInstallments} of {loan.totalInstallments} payments</Typography></Box></Stack><Button variant="segmented" startIcon={<EditIcon />} onClick={() => { setEditing(loan); setFormOpen(true); }}>Edit</Button></Stack>
      <Stack spacing={1}><Stack direction="row" justifyContent="space-between" alignItems="baseline"><Typography variant="sectionLabel">Loan progress</Typography><Typography variant="sectionLabel">{progress.progressPercent.toFixed(0)}%</Typography></Stack><Box sx={{ display: 'grid', gridTemplateColumns: `repeat(${loan.totalInstallments}, minmax(2px, 1fr))`, gap: { xs: 0.25, sm: 0.375 } }}>{Array.from({ length: loan.totalInstallments }, (_, index) => <Paper key={index} variant={index < progress.paidInstallments ? 'loanProgressSegmentPaid' : 'loanProgressSegment'} sx={{ height: 42 }} />)}</Box><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" spacing={1}><Typography variant="body2" color="text.secondary"><Money amount={progress.paidAmount} code={loan.currency} maxDigits={2} /> paid</Typography><Typography variant="body2" color="text.secondary"><Money amount={progress.remainingAmount} code={loan.currency} maxDigits={2} /> remaining</Typography></Stack></Stack>
      <Grid container spacing={2}><Grid size={6}><Typography component="div" variant="fieldHint" color="text.secondary">NEXT PAYMENT</Typography><Typography variant="loanMetric"><Money amount={Math.min(loan.installmentAmount, progress.remainingAmount)} code={loan.currency} maxDigits={2} /></Typography><Typography variant="loanMeta" color="text.secondary">{progress.nextDueDate ?? 'Complete'}</Typography></Grid><Grid size={6}><Typography component="div" variant="fieldHint" color="text.secondary">PAYOFF</Typography><Typography variant="loanMetric">{progress.remainingInstallments} months</Typography><Typography variant="loanMeta" color="text.secondary">{progress.payoffDate}</Typography></Grid></Grid>
      <Box><Stack direction="row" alignItems="center" spacing={1}><CalendarMonthIcon color={shortfall > 0 ? 'warning' : 'success'} /><Typography variant="body1">{shortfall > 0 ? <>Add <Money amount={shortfall} code={loan.currency} maxDigits={2} /> to {account?.name ?? 'the payment account'}</> : `${account?.name ?? 'Payment account'} is ready`}</Typography></Stack></Box>
      <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1.5} alignItems={{ sm: 'center' }}><Button variant="contained" onClick={() => setPaying(loan)} disabled={loan.status !== 'active' || progress.remainingAmount <= 0}>Record payment</Button><Chip label={loan.status === 'paid' ? 'Paid off' : shortfall > 0 ? 'Needs funding' : 'Ready'} color={loan.status === 'paid' || shortfall === 0 ? 'success' : 'warning'} /></Stack>
    </Stack></CardContent></Card></Grid>; })}</Grid>}
    <LoanDialog key={`loan-form-${editing?.id ?? 'new'}-${formOpen}`} accounts={accounts} loan={editing} open={formOpen} busy={createLoan.isPending || updateLoan.isPending} onClose={() => { setFormOpen(false); setEditing(null); }} onSave={save} /><LoanPaymentDialog key={`loan-payment-${paying?.id ?? 'closed'}`} loan={paying} open={Boolean(paying)} busy={recordPayment.isPending} onClose={() => setPaying(null)} onSave={pay} />
  </Stack>;
}
