import type { MessageTemplateInput } from '@/libs/messageTemplates';

/**
 * The bank regexes the built-in parser uses, surfaced as a duplicable
 * catalog. Duplicating one stores a household copy that — because
 * `overrideBuiltIn` is on — runs BEFORE the built-in rules, so users can
 * loosen or adapt a rule for message variants the stock regex misses.
 *
 * The catalog mirrors every transaction-producing built-in rule. Absent on
 * purpose: the Phone Banking Transfer legs (the built-in parser merges their
 * debit/credit messages into one transfer, which duplicated overrides cannot
 * do — duplicating them would book the legs twice) and the credit-card
 * payment rules (payment notifications, not transactions).
 */
export type PredefinedMessageTemplate = MessageTemplateInput & {
  /** Sample message for the live tester, prefilled on duplicate. */
  sample: string;
};

export const PREDEFINED_MESSAGE_TEMPLATES: PredefinedMessageTemplate[] = [
  {
    name: 'Bank Misr — instant transfer in',
    pattern: String.raw`تم اضافة مبلغ\s*(?<amount>[\d,]+(?:\.\d{1,2})?)\s*(?<currency>[A-Z]{3})\s*الى (?:ال)?حساب(?:ي|ى)?\s*رقم\s*[x*]*(?<last4>\d{4})\s*فى\s*\d{2}-[A-Z]{3}-\d{4}\s*عن طريق التحويل اللحظي`,
    kind: 'income',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: null,
    dateFormat: null,
    merchantGroup: null,
    last4Group: 'last4',
    cardKind: 'debit',
    bankId: 'banque-misr',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'تم اضافة مبلغ 1980EGP الى حساب رقم xxx7391 فى 30-AUG-2026 عن طريق التحويل اللحظي',
  },
  {
    name: 'Bank Misr — instant transfer in from a named sender',
    pattern: String.raw`تم إضافة تحويل لحظي الي بطاقة رقم\s*(?<last4>[\dx*]+)\s*بمبلغ\s*(?<amount>[\d,]+(?:\.\d{1,2})?)\s*(?:جم|(?<currency>[A-Z]{3}))?\s*من\s*(?<merchant>.+?)\s*رقم مرجعي\s*(?<reference>\d+)\s*يوم\s*(?<date>\d{2}/\d{2}/\d{4})`,
    kind: 'income',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'dd/MM/yyyy',
    merchantGroup: 'merchant',
    last4Group: 'last4',
    cardKind: 'debit',
    bankId: 'banque-misr',
    descriptionGroup: null,
    referenceGroup: 'reference',
    overrideBuiltIn: true,
    isActive: true,
    sample: 'تم إضافة تحويل لحظي الي بطاقة رقم 452829******2508 بمبلغ 3000 من MOHAMED SAID MAHMOUD MOHAMED رقم مرجعي 184104 يوم 18/11/2025 الساعه 14:28 للمزيد اتصل علي 19888',
  },
  {
    name: 'Bank Misr — instant transfer out',
    pattern: String.raw`تم تحويل مبلغ\s*(?<amount>[\d,]+(?:\.\d{1,2})?)\s*(?<currency>[A-Z]{3})\s*من (?:ال)?حساب(?:ي|ى)?\s*رقم\s*[x*]*(?<last4>\d{4})\s*فى\s*\d{2}-[A-Z]{3}-\d{4}\s*عن طريق التحويل اللحظي`,
    kind: 'expense',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: null,
    dateFormat: null,
    merchantGroup: null,
    last4Group: 'last4',
    cardKind: 'debit',
    bankId: 'banque-misr',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'تم تحويل مبلغ 20,000EGP من حساب رقم xxx7391 فى 30-AUG-2026 عن طريق التحويل اللحظي',
  },
  {
    name: 'Bank Misr — instant transfer out to a named beneficiary',
    pattern: String.raw`تم تنفيذ تحويل لحظي من حسابكم رقم\s*(?<last4>[\dx*]+)\s*بمبلغ\s*(?<amount>[\d,]+(?:\.\d{1,2})?)\s*(?:جم|(?<currency>[A-Z]{3}))?\s*[إا]لى\s*(?<merchant>.+?)\s*رقم مرجعي\s*(?<reference>\d+)\s*يوم\s*(?<date>\d{2}/\d{2}/\d{4})`,
    kind: 'expense',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'dd/MM/yyyy',
    merchantGroup: 'merchant',
    last4Group: 'last4',
    cardKind: 'debit',
    bankId: 'banque-misr',
    descriptionGroup: null,
    referenceGroup: 'reference',
    overrideBuiltIn: true,
    isActive: true,
    sample: 'تم تنفيذ تحويل لحظي من حسابكم رقم 0634701368999001 بمبلغ 500 جم إلى GHADEER FATHY MOHAMED رقم مرجعي 123456 يوم 25/03/2026 الساعه 10:11 للمزيد اتصل ب 19888',
  },
  {
    name: 'Bank Misr — credit card charge',
    pattern: String.raw`بطاقة\s*(?:بنك\s*مصر)?\s*(?:ال)?ائتمانية\s*(?:(?:المنتهية\s*)?ب?ـ?\s*\*{0,4}\s*)?(?<last4>\d{4})\s*[،,]?\s*تم خصم\s*(?:مبلغ\s*)?(?:(?<currency>[A-Z]{3})\s*)?(?<amount>[\d,]+(?:\.\d{1,2})?)\s*(?:[A-Z]{3})?\s*(?:في|فى)\s*(?<merchant>.+?)\s*(?:[A-Z]{2}|>)?\s*بتاريخ\s*(?<date>\d{2}/\d{2}/\d{4})`,
    kind: 'expense',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'dd/MM/yyyy',
    merchantGroup: 'merchant',
    last4Group: 'last4',
    cardKind: 'credit',
    bankId: 'banque-misr',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'عميلنا العزيز، شكرًا لاستخدامكم بطاقة بنك مصر الائتمانية *2508، تم خصم مبلغ EGP 10 في WE-Mobile-Pre بتاريخ 27/08/2026',
  },
  {
    name: 'Bank Misr — card purchase refund',
    pattern: String.raw`تم رد المعاملة بقيمة\s*(?<amount>[\d,]+(?:\.\d{1,2})?)\s*(?:جم|(?<currency>[A-Z]{3}))?\s*للبطاقة\s*[x*]*(?<last4>[\dx*]+)\s*[،,]?\s*بتاريخ\s*(?<date>\d{2}/\d{2}/\d{4})\s*من\s*(?<merchant>.+?)[،,]`,
    kind: 'income',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'dd/MM/yyyy',
    merchantGroup: 'merchant',
    last4Group: 'last4',
    cardKind: 'credit',
    bankId: 'banque-misr',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'عميلنا العزيز، تم رد المعاملة بقيمة 1229EGP للبطاقة *****2508، بتاريخ 12/11/2025 من Uber ، للاطلاع على معاملاتكم اضغط bnkmsr.com/online',
  },
  {
    name: 'Bank Misr — ATM withdrawal',
    pattern: String.raw`بطاقة بنك مصر\s*\*+\s*(?<last4>\d{4})\s*[،,]?\s*تم الخصم مبلغ\s*(?:(?<currency>[A-Z]{3})\s*)?(?<amount>[\d,]+(?:\.\d{1,2})?)\s*(?:[A-Z]{3})?\s*الة رقم\s*\d+.*?يوم\s*(?<date>\d{2}\/\d{2})`,
    kind: 'transfer',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'dd/MM',
    merchantGroup: null,
    last4Group: 'last4',
    cardKind: 'debit',
    bankId: 'banque-misr',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'شكرًا لاستخدامك بطاقة بنك مصر ****8616 ، تم الخصم مبلغEGP 15000.00 الة رقم 01880117 يوم 25/08',
  },
  {
    name: 'Bank Misr — cash deposit at machine',
    pattern: String.raw`بطاقة بنك مصر\s*\*+\s*(?<last4>\d{4})\s*[،,]?\s*تم إضافة مبلغ\s*(?:(?<currency>[A-Z]{3})\s*)?(?<amount>[\d,]+(?:\.\d{1,2})?)\s*(?:[A-Z]{3})?\s*الة رقم\s*\d+.*?يوم\s*(?<date>\d{2}\/\d{2})`,
    kind: 'transfer',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'dd/MM',
    merchantGroup: null,
    last4Group: 'last4',
    cardKind: 'debit',
    bankId: 'banque-misr',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'شكرًا لاستخدامك بطاقة بنك مصر ****8616، تم إضافة مبلغEGP 9800.00 الة رقم 01880111 يوم 25/08',
  },
  {
    name: 'Bank Misr — branch cash deposit',
    pattern: String.raw`تم [إا]?يداع مبلغ\s*(?<amount>[\d,]+(?:\.\d{1,2})?)\s*(?:جم|(?<currency>[A-Z]{3}))?\s*فى (?:حساب|البطاقة)(?:ي|ى)?\s*رقم\s*[x*]*(?<last4>[\dx*]+)\s*فى\s*(?<date>\d{2}/\d{2}/\d{4})`,
    kind: 'transfer',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'dd/MM/yyyy',
    merchantGroup: null,
    last4Group: 'last4',
    cardKind: 'debit',
    bankId: 'banque-misr',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'تم ايداع مبلغ 5000EGP فى حساب رقم xxx7391 فى 15/06/2026',
  },
  {
    name: 'Bank Misr — branch cash withdrawal',
    pattern: String.raw`تم سحب مبلغ\s*(?<amount>[\d,]+(?:\.\d{1,2})?)\s*(?:جم|(?<currency>[A-Z]{3}))?\s*نقدا?[ً]?\s*من حساب(?:ي|ى)?\s*رقم\s*[x*]*(?<last4>[\dx*]+)\s*فى\s*(?<date>\d{2}/\d{2}/\d{4})`,
    kind: 'transfer',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'dd/MM/yyyy',
    merchantGroup: null,
    last4Group: 'last4',
    cardKind: 'debit',
    bankId: 'banque-misr',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'تم سحب مبلغ 200USD نقداً من حساب رقم xxx7391 فى 12/06/2026',
  },
  {
    name: 'HSBC — debit card purchase',
    pattern: String.raw`From HSBC:\s*\d{2}[A-Z]{3}\d{2}\s*(?<merchant>.+?)\s+Purchase from\s+\S+\s+(?<currency>[A-Z]{3})\s+(?<amount>[\d,]+(?:\.\d{1,2})?)-`,
    kind: 'expense',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: null,
    dateFormat: null,
    merchantGroup: 'merchant',
    last4Group: null,
    cardKind: 'debit',
    bankId: 'hsbc',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'From HSBC: 31JUL26 FAWRY*BEANOS Purchase from 074-096***-001 EGP 325.00- Your available balance is EGP 43,356.16',
  },
  {
    name: 'HSBC — credit card purchase',
    pattern: String.raw`(?:Your|HSBC) Credit Card ending (?:with\s*)?\*{3}\s*(?<last4>\d{4}).*?used for\s+(?<currency>[A-Z]{3})\s+(?<amount>[\d,]+(?:\.\d{1,2})?)\s+on\s+(?<date>\d{2}/\d{2}/\d{4})\s+at\s+(?<merchant>.+?)(?:\.\s*Your available limit|$)`,
    kind: 'expense',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'dd/MM/yyyy',
    merchantGroup: 'merchant',
    last4Group: 'last4',
    cardKind: 'credit',
    bankId: 'hsbc',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'Your Credit Card ending with *** 7281 has been used for EGP 999.99 on 19/07/2026 at OPENAI *CHATGPT SUBSCR. Your available limit is EGP 52680.20',
  },
  {
    name: 'HSBC — IPN inward transfer (income)',
    pattern: String.raw`\*+(?<last4>\d{4})\s+was credited with IPN inward transfer for\s+(?<currency>[A-Z]{3})\s+(?<amount>[\d,]+(?:\.\d{1,2})?)\s+on\s+(?<date>\d{2}-\d{2}-\d{4})\s+(?:\d{2}:\d{2})?\s*from\s+(?<merchant>.+?)\s+with reference\s+(?<reference>[A-Za-z0-9-]+)`,
    kind: 'income',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'dd-MM-yyyy',
    merchantGroup: 'merchant',
    last4Group: 'last4',
    cardKind: 'debit',
    bankId: 'hsbc',
    descriptionGroup: null,
    referenceGroup: 'reference',
    overrideBuiltIn: true,
    isActive: true,
    sample: '********1001 was credited with IPN inward transfer for EGP 225.00 on 17-07-2026 04:06 from person314271@instapay with reference e33925a9.',
  },
  {
    name: 'HSBC — IPN purchase (expense)',
    pattern: String.raw`\*+(?<last4>\d{4})\s+was debited with IPN purchase for\s+(?<currency>[A-Z]{3})\s+(?<amount>[\d,]+(?:\.\d{1,2})?)\s+on\s+(?<date>\d{2}-\d{2}-\d{4})\s+(?:\d{2}:\d{2})?\s*from\s+(?<merchant>.+?)\s+with reference\s+(?<reference>[A-Za-z0-9-]+)`,
    kind: 'expense',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'dd-MM-yyyy',
    merchantGroup: 'merchant',
    last4Group: 'last4',
    cardKind: 'debit',
    bankId: 'hsbc',
    descriptionGroup: null,
    referenceGroup: 'reference',
    overrideBuiltIn: true,
    isActive: true,
    sample: 'Your HSBC Account ********1001 was debited with IPN purchase for EGP 124.00 on 09-08-2026 01:39 from Nat Gas with reference c94e683c.',
  },
  {
    name: 'HSBC — IPN outward transfer (expense)',
    pattern: String.raw`\*+(?<last4>\d{4})\s+was debited with IPN outward transfer for\s+(?<currency>[A-Z]{3})\s+(?<amount>[\d,]+(?:\.\d{1,2})?)\s+on\s+(?<date>\d{2}-\d{2}-\d{4})\s+(?:\d{2}:\d{2})?\s*to\s+(?<merchant>.+?)\s+with reference\s+(?<reference>[A-Za-z0-9-]+)`,
    kind: 'expense',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'dd-MM-yyyy',
    merchantGroup: 'merchant',
    last4Group: 'last4',
    cardKind: 'debit',
    bankId: 'hsbc',
    descriptionGroup: null,
    referenceGroup: 'reference',
    overrideBuiltIn: true,
    isActive: true,
    sample: 'Your HSBC Account ********9001 was debited with IPN outward transfer for EGP 30,000.00 on 18-02-2023 13:17 to AHMED SAFAA ALI IBRAHIM with reference bfac9728.',
  },
  {
    name: 'HSBC — IPN reversal (money returned)',
    pattern: String.raw`\*+(?<last4>\d{4})\s+was reversed with IPN outward transfer for\s+(?<currency>[A-Z]{3})\s+(?<amount>[\d,]+(?:\.\d{1,2})?)\s+on\s+(?<date>\d{2}-\d{2}-\d{4})\s+(?:\d{2}:\d{2})?\s*from\s+(?<merchant>.+?)\s+with reference\s+(?<reference>[A-Za-z0-9-]+)`,
    kind: 'income',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'dd-MM-yyyy',
    merchantGroup: 'merchant',
    last4Group: 'last4',
    cardKind: 'debit',
    bankId: 'hsbc',
    descriptionGroup: null,
    referenceGroup: 'reference',
    overrideBuiltIn: true,
    isActive: true,
    sample: 'Your HSBC Account ********9001 was reversed with IPN outward transfer for EGP 50,700.00 on 05-06-2023 18:43 from MOHAMED SAID MAHMOUD MOHAMED with reference 627b62dd.',
  },
  {
    name: 'HSBC — ATM cash withdrawal',
    pattern: String.raw`From HSBC:\s*(?<date>\d{2}[A-Z]{3}\d{2})\s+ATM Cash Withdrawal from\s+\S+\s+(?<currency>[A-Z]{3})\s+(?<amount>[\d,]+(?:\.\d{1,2})?)-`,
    kind: 'transfer',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'ddMMMyy',
    merchantGroup: null,
    last4Group: null,
    cardKind: 'debit',
    bankId: 'hsbc',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'From HSBC: 27JUL26 ATM Cash Withdrawal from 074-096***-001 EGP 4,000.00- Your available balance is EGP 50,171.95',
  },
  {
    name: 'HSBC — cash deposit at branch',
    pattern: String.raw`From HSBC:\s*(?<date>\d{2}[A-Z]{3}\d{2})\s+Cash Deposit to\s+\S+\s+(?<currency>[A-Z]{3})\s+(?<amount>[\d,]+(?:\.\d{1,2})?)\+`,
    kind: 'transfer',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'ddMMMyy',
    merchantGroup: null,
    last4Group: null,
    cardKind: 'debit',
    bankId: 'hsbc',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'From HSBC: 16AUG22 Cash Deposit to 074-069***-001 EGP 50,000.00+ Your available balance is EGP 95,235.85',
  },
  {
    name: 'HSBC — transfer debit',
    pattern: String.raw`From HSBC:\s*(?<date>\d{2}[A-Z]{3}\d{2})\s+Transfer from\s+\S+\s+(?<currency>[A-Z]{3})\s+(?<amount>[\d,]+(?:\.\d{1,2})?)-`,
    kind: 'expense',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'ddMMMyy',
    merchantGroup: null,
    last4Group: null,
    cardKind: 'debit',
    bankId: 'hsbc',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'From HSBC: 07JUL22 Transfer from 074-069***-001 EGP 32,147.00- Your available balance is EGP 987.11',
  },
  {
    name: 'HSBC — internet banking / TT payment in',
    pattern: String.raw`From HSBC:\s*(?<date>\d{2}[A-Z]{3}\d{2})\s+(?:Internet Banking )?(?:TT Payment|Transfer) to\s+\S+\s+(?<currency>[A-Z]{3})\s+(?<amount>[\d,]+(?:\.\d{1,2})?)\+`,
    kind: 'income',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'ddMMMyy',
    merchantGroup: null,
    last4Group: null,
    cardKind: 'debit',
    bankId: 'hsbc',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'From HSBC: 18NOV21 TT Payment to 074-069***-001 EGP 200,000.00+ Your available balance is EGP 206,464.42',
  },
  {
    name: 'HSBC — internet banking / TT payment out',
    pattern: String.raw`From HSBC:\s*(?<date>\d{2}[A-Z]{3}\d{2})\s+(?:Internet Banking )?(?:TT Payment|Transfer) from\s+\S+\s+(?<currency>[A-Z]{3})\s+(?<amount>[\d,]+(?:\.\d{1,2})?)-`,
    kind: 'expense',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'ddMMMyy',
    merchantGroup: null,
    last4Group: null,
    cardKind: 'debit',
    bankId: 'hsbc',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'From HSBC: 18JUL21 Internet Banking Transfer from 074-069***-001 EGP 1,000.00- Your available balance is EGP 30.67',
  },
  {
    name: 'HSBC — salary credit',
    pattern: String.raw`From HSBC:\s*(?<date>\d{2}[A-Z]{3}\d{2})\s+Salary to\s+\S+\s+(?<currency>[A-Z]{3})\s+(?<amount>[\d,]+(?:\.\d{1,2})?)\+`,
    kind: 'income',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'ddMMMyy',
    merchantGroup: null,
    last4Group: null,
    cardKind: 'debit',
    bankId: 'hsbc',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'From HSBC: 27JUL21 Salary to 074-069***-001 EGP 27,928.69+ Your available balance is EGP 28,959.36',
  },
  {
    name: 'HSBC — cheque debit',
    pattern: String.raw`From HSBC:\s*(?<date>\d{2}[A-Z]{3}\d{2})\s+Cheque from\s+\S+\s+with cheque no #(?<reference>\d+)\s+(?<currency>[A-Z]{3})\s+(?<amount>[\d,]+(?:\.\d{1,2})?)-`,
    kind: 'expense',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'ddMMMyy',
    merchantGroup: null,
    last4Group: null,
    cardKind: 'debit',
    bankId: 'hsbc',
    descriptionGroup: null,
    referenceGroup: 'reference',
    overrideBuiltIn: true,
    isActive: true,
    sample: 'From HSBC: 23NOV21 Cheque from 074-069***-001 with cheque no #107453 EGP 116,155.00- Your available balance is EGP 88,809.42',
  },
  {
    name: 'HSBC — cheque deposit',
    pattern: String.raw`From HSBC:\s*(?<date>\d{2}[A-Z]{3}\d{2})\s+Cheque to\s+\S+\s+(?<currency>[A-Z]{3})\s+(?<amount>[\d,]+(?:\.\d{1,2})?)\+`,
    kind: 'income',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'ddMMMyy',
    merchantGroup: null,
    last4Group: null,
    cardKind: 'debit',
    bankId: 'hsbc',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'From HSBC: 03AUG23 Cheque to 074-069***-001 EGP 37,500.00+',
  },
];
