import type { MessageTemplateInput } from '@/libs/messageTemplates';

/**
 * The bank regexes the built-in parser uses, surfaced as a duplicable
 * catalog. Duplicating one stores a household copy that — because
 * `overrideBuiltIn` is on — runs BEFORE the built-in rules, so users can
 * loosen or adapt a rule for message variants the stock regex misses.
 */
export type PredefinedMessageTemplate = MessageTemplateInput & {
  /** Sample message for the live tester, prefilled on duplicate. */
  sample: string;
};

export const PREDEFINED_MESSAGE_TEMPLATES: PredefinedMessageTemplate[] = [
  {
    name: 'Bank Misr — instant transfer in',
    pattern: String.raw`تم اضافة مبلغ\s*(?<amount>[\d,]+(?:\.\d{1,2})?)\s*(?<currency>[A-Z]{3})\s*الى (?:ال)?حساب(?:ي|ى)?\s*رقم\s*[x*]*(?<last4>\d{4})\s*فى\s*\d{2}-[A-Z]{3}-\d{4}\s*عن طريق التحويل اللحظي`,
    kind: 'income',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: null,
    dateFormat: null,
    merchantGroup: null,
    last4Group: 'last4',
    cardKind: 'debit',
    bankId: 'banque-misr',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'تم اضافة مبلغ 1980EGP الى حساب رقم xxx7391 فى 30-AUG-2026 عن طريق التحويل اللحظي',
  },
  {
    name: 'Bank Misr — instant transfer out',
    pattern: String.raw`تم تحويل مبلغ\s*(?<amount>[\d,]+(?:\.\d{1,2})?)\s*(?<currency>[A-Z]{3})\s*من (?:ال)?حساب(?:ي|ى)?\s*رقم\s*[x*]*(?<last4>\d{4})\s*فى\s*\d{2}-[A-Z]{3}-\d{4}\s*عن طريق التحويل اللحظي`,
    kind: 'expense',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: null,
    dateFormat: null,
    merchantGroup: null,
    last4Group: 'last4',
    cardKind: 'debit',
    bankId: 'banque-misr',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'تم تحويل مبلغ 20,000EGP من حساب رقم xxx7391 فى 30-AUG-2026 عن طريق التحويل اللحظي',
  },
  {
    name: 'Bank Misr — credit card charge',
    pattern: String.raw`بطاقة\s*(?:بنك\s*مصر)?\s*(?:ال)?ائتمانية\s*(?:(?:المنتهية\s*)?ب?ـ?\s*\*{0,4}\s*)?(?<last4>\d{4})\s*[،,]?\s*تم خصم\s*(?:مبلغ\s*)?(?:(?<currency>[A-Z]{3})\s*)?(?<amount>[\d,]+(?:\.\d{1,2})?)\s*(?:[A-Z]{3})?\s*(?:في|فى)\s*(?<merchant>.+?)\s*(?:[A-Z]{2}|>)?\s*بتاريخ\s*(?<date>\d{2}/\d{2}/\d{4})`,
    kind: 'expense',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'dd/MM/yyyy',
    merchantGroup: 'merchant',
    last4Group: 'last4',
    cardKind: 'credit',
    bankId: 'banque-misr',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'عميلنا العزيز، شكرًا لاستخدامكم بطاقة بنك مصر الائتمانية *2508، تم خصم مبلغ EGP 10 في WE-Mobile-Pre بتاريخ 27/08/2026',
  },
  {
    name: 'Bank Misr — ATM withdrawal',
    pattern: String.raw`بطاقة بنك مصر\s*\*+\s*(?<last4>\d{4})\s*[،,]?\s*تم الخصم مبلغ\s*(?:(?<currency>[A-Z]{3})\s*)?(?<amount>[\d,]+(?:\.\d{1,2})?)`,
    kind: 'transfer',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: null,
    dateFormat: null,
    merchantGroup: null,
    last4Group: 'last4',
    cardKind: 'debit',
    bankId: 'banque-misr',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'شكرًا لاستخدامك بطاقة بنك مصر ****8616 ، تم الخصم مبلغEGP 15000.00 الة رقم 01880117 يوم 25/08',
  },
  {
    name: 'Bank Misr — cash deposit at machine',
    pattern: String.raw`بطاقة بنك مصر\s*\*+\s*(?<last4>\d{4})\s*[،,]?\s*تم إضافة مبلغ\s*(?:(?<currency>[A-Z]{3})\s*)?(?<amount>[\d,]+(?:\.\d{1,2})?)`,
    kind: 'transfer',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: null,
    dateFormat: null,
    merchantGroup: null,
    last4Group: 'last4',
    cardKind: 'debit',
    bankId: 'banque-misr',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'شكرًا لاستخدامك بطاقة بنك مصر ****8616، تم إضافة مبلغEGP 9800.00 الة رقم 01880111 يوم 25/08',
  },
  {
    name: 'HSBC — debit card purchase',
    pattern: String.raw`From HSBC:\s*\d{2}[A-Z]{3}\d{2}\s*(?<merchant>.+?)\s+Purchase from\s+\S+\s+(?<currency>[A-Z]{3})\s+(?<amount>[\d,]+(?:\.\d{1,2})?)-`,
    kind: 'expense',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: null,
    dateFormat: null,
    merchantGroup: 'merchant',
    last4Group: null,
    cardKind: 'debit',
    bankId: 'hsbc',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'From HSBC: 31JUL26 FAWRY*BEANOS Purchase from 074-096***-001 EGP 325.00- Your available balance is EGP 43,356.16',
  },
  {
    name: 'HSBC — credit card purchase',
    pattern: String.raw`(?:Your|HSBC) Credit Card ending (?:with\s*)?\*{3}\s*(?<last4>\d{4}).*?used for\s+(?<currency>[A-Z]{3})\s+(?<amount>[\d,]+(?:\.\d{1,2})?)\s+on\s+(?<date>\d{2}/\d{2}/\d{4})\s+at\s+(?<merchant>.+?)(?:\.\s*Your available limit|$)`,
    kind: 'expense',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'dd/MM/yyyy',
    merchantGroup: 'merchant',
    last4Group: 'last4',
    cardKind: 'credit',
    bankId: 'hsbc',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'Your Credit Card ending with *** 7281 has been used for EGP 999.99 on 19/07/2026 at OPENAI *CHATGPT SUBSCR. Your available limit is EGP 52680.20',
  },
  {
    name: 'HSBC — IPN inward transfer (income)',
    pattern: String.raw`\*+(?<last4>\d{4})\s+was credited with IPN inward transfer for\s+(?<currency>[A-Z]{3})\s+(?<amount>[\d,]+(?:\.\d{1,2})?)\s+on\s+(?<date>\d{2}-\d{2}-\d{4})`,
    kind: 'income',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'dd-MM-yyyy',
    merchantGroup: null,
    last4Group: 'last4',
    cardKind: 'debit',
    bankId: 'hsbc',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: '********1001 was credited with IPN inward transfer for EGP 225.00 on 17-07-2026 04:06 from person314271@instapay with reference e33925a9.',
  },
  {
    name: 'HSBC — IPN purchase (expense)',
    pattern: String.raw`\*+(?<last4>\d{4})\s+was debited with IPN purchase for\s+(?<currency>[A-Z]{3})\s+(?<amount>[\d,]+(?:\.\d{1,2})?)\s+on\s+(?<date>\d{2}-\d{2}-\d{4})`,
    kind: 'expense',
    amountGroup: 'amount',
    currencyGroup: 'currency',
    currency: 'EGP',
    dateGroup: 'date',
    dateFormat: 'dd-MM-yyyy',
    merchantGroup: null,
    last4Group: 'last4',
    cardKind: 'debit',
    bankId: 'hsbc',
    descriptionGroup: null,
    overrideBuiltIn: true,
    isActive: true,
    sample: 'Your HSBC Account ********1001 was debited with IPN purchase for EGP 124.00 on 09-08-2026 01:39 from Nat Gas with reference c94e683c.',
  },
];
